import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const base = process.env.BASE_URL || 'http://localhost:3000';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
let createdCode;
try {
  await page.goto(base);
  await page.getByRole('heading', { name: 'A little link. A lot of possibility.' }).waitFor();
  await page.getByRole('button', { name: 'Design inspiration collection', exact: true }).waitFor();
  await page.evaluate(() => document.fonts.ready);
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/dashboard.png', fullPage: true });
  await page.getByRole('button', { name: 'Customize your link' }).click();
  await page.getByLabel('Destination URL', { exact: true }).fill('https://example.com/browser-test');
  await page.getByPlaceholder('e.g. My portfolio').fill('Browser test link');
  await page.getByRole('button', { name: 'Shorten link', exact: true }).click();
  await page.getByRole('button', { name: 'Browser test link', exact: true }).waitFor();
  const data = await (await page.request.get(`${base}/shorten`)).json();
  createdCode = data.links.find(l => l.title === 'Browser test link').shortCode;
  await page.getByRole('button', { name: 'Actions for Browser test link', exact: true }).click();
  await page.getByRole('button', { name: 'Edit link', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Link title', { exact: true }).fill('Browser test edited');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await page.getByRole('button', { name: 'Browser test edited', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Actions for Browser test edited', exact: true }).click();
  await page.getByRole('button', { name: 'Archive link', exact: true }).click();
  await page.getByRole('button', { name: 'Archived', exact: true }).click();
  await page.getByRole('button', { name: 'Browser test edited', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Actions for Browser test edited', exact: true }).click();
  await page.getByRole('button', { name: 'Delete link', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete link', exact: true }).click();
  await page.getByRole('button', { name: 'Browser test edited', exact: true }).waitFor({ state: 'hidden' });
  createdCode = undefined;
  await page.getByRole('button', { name: 'Analytics', exact: true }).click();
  await page.getByRole('heading', { name: 'Clicks over time' }).waitFor();
  await page.getByRole('button', { name: 'API & docs', exact: true }).click();
  await page.getByRole('heading', { name: 'A simple API for every connection.' }).waitFor();
  const download = await page.request.get(`${base}/downloads/shortly-source.zip`);
  assert.equal(download.status(), 200, 'Source ZIP should be downloadable');
  assert.equal((await download.body()).subarray(0, 2).toString(), 'PK');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.getByRole('heading', { name: 'A little link. A lot of possibility.' }).waitFor();
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'Mobile page should not overflow');
  assert.deepEqual(errors, [], 'No client runtime errors');
  console.log('PASS: desktop render, creation, edit, archive, filters, delete, analytics, docs, ZIP download, mobile navigation, and responsive width.');
} finally {
  if (createdCode) await page.request.delete(`${base}/shorten/${createdCode}`);
  await browser.close();
}
